### ISSUE TITLE
Does not compile anymore

### ISSUE THREAD

**Issue by sdroege** [ford-prefect/gst-plugin-s3#1]
There was a lot of refactoring done at https://github.com/sdroege/gst-plugin-rs/ and this does not compile anymore now.

Also rusoto has a streaming mode now, which might make sense to use here. And it might make sense to use directly https://github.com/sdroege/gst-plugin-rs/blob/master/gst-plugin/src/base_src.rs instead of the simplified Source trait (it gives access to unlock/unlock_stop and others).

**Comment by ford-prefect** [comment]
I'm seeing this when I change my dependency to current `gst-plugin-rs`:

```
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/sdroege/gst-plugin-rs`
    Updating git repository `https://github.com/sdroege/gstreamer-rs`
    Updating git repository `https://github.com/gtk-rs/glib`
    Updating git repository `https://github.com/gtk-rs/sys`
error: no matching version `= 0.3.2` found for package `gobject-sys` (required by `gstreamer-sys`)
location searched: https://github.com/gtk-rs/sys.git#a0fdcfee
versions found: 0.4.0
```

Any ideas?

**Comment by sdroege** [comment]
That's not really a fix though, just a workaround :)

**Comment by ford-prefect** [comment]
Of course. :) Was just checkpointing my code. Still updating to gst-plugin-rs master.
